---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: business
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: business
  replicas: 2
  template:
    metadata:
      labels:
        app: business
    spec:
      containers:
      - name: business
        image: iuliiaioana/business-app:v5
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: business
  namespace: default
  labels:
    app: business
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: business
  type: LoadBalancer
