# Configurare de cluster cu trei noduri (dintre care doi workeri)
kind: Cluster # precizăm ce dorim să creăm: cluster, pod, etc.
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker