apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS USER;
    USE USER;
    CREATE TABLE IF NOT EXISTS USERS(id INT AUTO_INCREMENT primary key NOT NULL, name VARCHAR(100));
    CREATE TABLE IF NOT EXISTS PARTNERSHIP(id INT AUTO_INCREMENT primary key NOT NULL, user1 int, user2 int);
    INSERT INTO USERS(name) VALUES ('Ana');
    INSERT INTO USERS(name) VALUES ('Mihai');
    INSERT INTO USERS(name) VALUES ('Andreea');
    INSERT INTO USERS(name) VALUES ('Lorena');
    INSERT INTO USERS(name) VALUES ('Lavinia');
    INSERT INTO USERS(name) VALUES ('Iulia');
